### ISSUE TITLE
Never Upload .env to git repo [SECURITY ISSUE]

### ISSUE THREAD

**Issue by Kashifwahaj** [MohammadJunaidG/myE-ComProject#1]
As per my understanding of these things, I never suggest pushing a .env file to git, for managing environment variables make at least two files: 
1. .env.example where you just put keys, not values this file can be pushed to git.
2. .env is meant for running environments like local, development, staging, production, etc. you can have as many .env files as you need for each environment(.env.local, .env.staging, .env.production, etc.)

**Comment by MohammadJunaidG** [comment]
Okay.
Got your point.
