### ISSUE TITLE
Never put Secret Data in code files, [SECURITY ISSUE]

### ISSUE THREAD

**Issue by Kashifwahaj** [MohammadJunaidG/myE-ComProject#2]
https://github.com/MohammadJunaidG/myE-ComProject/blob/9f61488c2cfd7ae0c10b579aaa8c08c5d2c9f170/configs/db.configs.js#L5

As per my understanding of these things to date,
The main reason for having .env files is to never have to put secret text (like username, DB name, any password) on code files,
make sure no sensitive information will go to the GitHub repo, so put all the sensitive/secret data in .env only.

**Comment by MohammadJunaidG** [comment]
Okay!
Noted your suggestions.
