### ISSUE TITLE
Request Data Validation [POTENTIAL SECURITY ISSUE]

### ISSUE THREAD

**Issue by Kashifwahaj** [MohammadJunaidG/myE-ComProject#3]
As per my understanding to date, along side from client side form/api validation, application must have server side request data validation also, so on every controller function, I suggest adding incoming data validation, you can found npm libariries like yup, zod , etc. for data validation.

**Comment by MohammadJunaidG** [comment]
Your concern is noted.
I never come across this issue.
I will search for it and try to implement it in my code.
Thanks for your review.
